const state=JSON.parse(localStorage.getItem("fb-phone")||'{"income":12940,"purchases":3180,"deductible":2481,"mileage":428,"rate":0.30}');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
function render(){income.textContent=money(state.income);purchases.textContent=money(state.purchases);mileage.textContent=state.mileage+" mi";deductible.textContent=money(state.deductible);tax.textContent=money(Math.max(0,state.income-state.deductible)*state.rate);savings.textContent=money(state.deductible*state.rate)}
function save(){localStorage.setItem("fb-phone",JSON.stringify(state));render()}
function openSheet(title,label,html){sheetTitle.textContent=title;sheetLabel.textContent=label;sheetBody.innerHTML=html;sheet.classList.remove("hidden");shade.classList.remove("hidden")}
function closeSheet(){sheet.classList.add("hidden");shade.classList.add("hidden")}
close.onclick=closeSheet;shade.onclick=closeSheet;
const pages={
income:()=>openSheet("Income","AT A GLANCE",`<div class="sheet-block"><div class="row"><span>Total received</span><strong>${money(state.income)}</strong></div></div><div class="sheet-block"><div class="row"><span>Paid invoices</span><strong>5</strong></div></div><p class="muted">Income from Invoice and imported deposits appears here automatically.</p>`),
purchases:()=>openSheet("Purchases","AT A GLANCE",`<div class="sheet-block"><div class="row"><span>Total purchases</span><strong>${money(state.purchases)}</strong></div></div><div class="sheet-block"><div class="row"><span>Deductible</span><strong>${money(state.deductible)}</strong></div></div><div class="sheet-block"><div class="row"><span>Needs review</span><strong>4</strong></div></div>`),
mileage:()=>openSheet("Mileage","AT A GLANCE",`<div class="sheet-block"><div class="row"><span>Business miles</span><strong>${state.mileage} mi</strong></div></div><div class="sheet-block"><div class="row"><span>Estimated deduction</span><strong>${money(state.mileage*.67)}</strong></div></div>`),
impact:()=>openSheet("Adjust impact","LIVE TAX ESTIMATE",`<div class="sheet-block"><label>Deductible expenses</label><input id="dInput" type="number" value="${state.deductible}"></div><div class="sheet-block"><label>Estimated tax rate</label><select id="rInput">${[.2,.25,.3,.35].map(v=>`<option value="${v}" ${state.rate===v?"selected":""}>${v*100}%</option>`).join("")}</select></div><button class="save" id="saveImpact">Update snapshot</button>`),
review:()=>openSheet("Needs review","4 PURCHASES",`<div class="sheet-block"><strong>Amazon · $84</strong><p class="muted">Could be equipment, office supplies, or personal.</p></div><div class="sheet-block"><strong>Home Depot · $146</strong><p class="muted">Business use is not confirmed.</p></div><div class="sheet-block"><strong>T-Mobile · $132</strong><p class="muted">Choose a business-use percentage.</p></div><div class="sheet-block"><strong>Marriott · $418</strong><p class="muted">Possible work travel.</p></div>`),
activity:()=>openSheet("Activity","RECENT CHANGES",activityList.innerHTML),
invoices:()=>openSheet("Invoices","CONNECTED APP",`<p class="muted">Open Invoice to create, send, and manage client invoices. Paid invoices flow back into Financial Brain.</p><button class="save">Open Invoice</button>`)
};
$$("[data-sheet]").forEach(b=>b.onclick=()=>pages[b.dataset.sheet]?.());
function quickAdd(kind){const labels={income:"Add income",purchase:"Add purchase",mileage:"Add mileage",receipt:"Add receipt"};const field=kind==="receipt"?'<p class="muted">Choose a photo or PDF receipt.</p><input type="file" accept="image/*,.pdf">':`<label>Amount</label><input id="amount" type="number" placeholder="0">`;openSheet(labels[kind],"QUICK ENTRY",`<div class="sheet-block">${field}</div><button class="save" id="quickSave">Save</button>`);quickSave.onclick=()=>{const v=Number($("#amount")?.value||0);if(kind==="income")state.income+=v;if(kind==="purchase"){state.purchases+=v;state.deductible+=v}if(kind==="mileage"){state.mileage+=v;state.deductible+=v*.67}save();closeSheet()}}
$$("[data-add]").forEach(b=>b.onclick=()=>quickAdd(b.dataset.add));
plus.onclick=()=>openSheet("Add something","QUICK ENTRY",`<div class="quick"><div><button onclick="quickAdd('income')">Income</button><button onclick="quickAdd('purchase')">Purchase</button><button onclick="quickAdd('mileage')">Mileage</button><button onclick="quickAdd('receipt')">Receipt</button></div></div>`);
document.addEventListener("click",e=>{if(e.target.id==="saveImpact"){state.deductible=Number(dInput.value);state.rate=Number(rInput.value);save();closeSheet()}});
window.quickAdd=quickAdd;render();